/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/geocode/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reverse */
        get: operations["reverse_api_v1_geocode_reverse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geocode/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_geocode_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Locations */
        get: operations["get_locations_api_v1_locations_get"];
        put?: never;
        /** Post Location */
        post: operations["post_location_api_v1_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Location */
        delete: operations["remove_location_api_v1_locations__location_id__delete"];
        options?: never;
        head?: never;
        /** Patch Location */
        patch: operations["patch_location_api_v1_locations__location_id__patch"];
        trace?: never;
    };
    "/api/v1/locations/{location_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast */
        get: operations["get_forecast_api_v1_locations__location_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}/forecast-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast History */
        get: operations["get_forecast_history_api_v1_locations__location_id__forecast_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The anonymous visitor's profile. The first call issues the visitor cookie.
         */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preferences */
        patch: operations["update_preferences_api_v1_me_preferences_patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Condition */
        Condition: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /**
         * Confidence
         * @description Ensemble agreement. Not a calibrated probability of being correct.
         */
        Confidence: {
            /** Level */
            level: ("high" | "medium" | "low") | null;
            /** Score */
            score: number | null;
        };
        /** CurrentConditions */
        CurrentConditions: {
            /** Cloud Cover */
            cloud_cover: number | null;
            condition: components["schemas"]["Condition"];
            /** Dewpoint */
            dewpoint: number | null;
            /** Feels Like */
            feels_like: number | null;
            /** Humidity */
            humidity: number | null;
            /** Precip Probability */
            precip_probability: number | null;
            /**
             * Source
             * @enum {string}
             */
            source: "forecast" | "observation";
            /** Temperature */
            temperature: number | null;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Wind Direction */
            wind_direction: string | null;
            /** Wind Direction Deg */
            wind_direction_deg: number | null;
            /** Wind Speed */
            wind_speed: number | null;
        };
        /** DailyForecast */
        DailyForecast: {
            condition: components["schemas"]["Condition"];
            confidence: components["schemas"]["DayConfidence"];
            /**
             * Date
             * Format: date
             */
            date: string;
            high: components["schemas"]["Range"];
            high_distribution: components["schemas"]["Distribution"] | null;
            /** Hours Covered */
            hours_covered: number | null;
            low: components["schemas"]["Range"];
            /** Members */
            members: number | null;
            precip_amount: components["schemas"]["Spread"];
            /** Precip Exceedance */
            precip_exceedance: {
                [key: string]: number;
            } | null;
            /** Precip Probability */
            precip_probability: number | null;
            wind_max: components["schemas"]["Spread"];
        };
        /** DayConfidence */
        DayConfidence: {
            overall: components["schemas"]["Confidence"];
            precipitation: components["schemas"]["Confidence"];
            /** Precipitation Summary */
            precipitation_summary: string;
            temperature: components["schemas"]["Confidence"];
            /** Temperature Summary */
            temperature_summary: string;
        };
        /** Distribution */
        Distribution: {
            /** Counts */
            counts: number[];
            /** Edges */
            edges: number[];
        };
        /** Forecast */
        Forecast: {
            current?: components["schemas"]["CurrentConditions"] | null;
            /**
             * Daily
             * @default []
             */
            daily: components["schemas"]["DailyForecast"][];
            /**
             * Hourly
             * @default []
             */
            hourly: components["schemas"]["HourlyForecast"][];
            location: components["schemas"]["Location"];
            /** Message */
            message?: string | null;
            model_run?: components["schemas"]["ModelRun"] | null;
            rain_outlook?: components["schemas"]["RainOutlook"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "processing" | "unavailable";
            summary?: components["schemas"]["Summary"] | null;
            units: components["schemas"]["Units"];
        };
        /** ForecastHistory */
        ForecastHistory: {
            /** Available Dates */
            available_dates: string[];
            /** Entries */
            entries: components["schemas"]["HistoryEntry"][];
            location: components["schemas"]["Location"];
            /**
             * Metric
             * @enum {string}
             */
            metric: "temperature" | "precipitation" | "wind";
            /** Target Date */
            target_date?: string | null;
            /** Target Time */
            target_time?: string | null;
            units: components["schemas"]["Units"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Lead Time Hours */
            lead_time_hours: number | null;
            model_run: components["schemas"]["ModelRun"];
            /** Values */
            values: {
                [key: string]: components["schemas"]["HistoryValue"];
            };
        };
        /** HistoryValue */
        HistoryValue: {
            /** P10 */
            p10?: number | null;
            /** P50 */
            p50?: number | null;
            /** P90 */
            p90?: number | null;
            /** Probability */
            probability?: number | null;
        };
        /** HourlyForecast */
        HourlyForecast: {
            /** Cloud Cover */
            cloud_cover: number | null;
            condition: components["schemas"]["Condition"];
            confidence: components["schemas"]["Confidence"];
            /** Dewpoint */
            dewpoint: number | null;
            /** Feels Like */
            feels_like: number | null;
            /** Lead Time Hours */
            lead_time_hours: number;
            precip_amount: components["schemas"]["Spread"];
            /** Precip Exceedance */
            precip_exceedance: {
                [key: string]: number;
            } | null;
            /** Precip Probability */
            precip_probability: number | null;
            temperature: components["schemas"]["Range"];
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Wind Direction */
            wind_direction: string | null;
            /** Wind Direction Deg */
            wind_direction_deg: number | null;
            wind_speed: components["schemas"]["Spread"];
        };
        /**
         * Location
         * @description A saved location. Exact coordinates are returned only to its owner.
         */
        Location: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Default */
            is_default: boolean;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
        };
        /** LocationCreate */
        LocationCreate: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
        };
        /** LocationUpdate */
        LocationUpdate: {
            /** Is Default */
            is_default?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /** Me */
        Me: {
            /** Default Location Id */
            default_location_id: string | null;
            /** Location Count */
            location_count: number;
            preferences: components["schemas"]["Preferences"];
            visitor: components["schemas"]["VisitorProfile"];
        };
        /** ModelRun */
        ModelRun: {
            /** Forecast Horizon Hours */
            forecast_horizon_hours: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /**
             * Initialization Time
             * Format: date-time
             */
            initialization_time: string;
            /** Model */
            model: string;
            /** Status */
            status: string;
        };
        /** Place */
        Place: {
            /** Country Code */
            country_code?: string | null;
            /** Label */
            label: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
        };
        /** Preferences */
        Preferences: {
            /**
             * Precipitation Unit
             * @enum {string}
             */
            precipitation_unit: "in" | "mm";
            /** Show Advanced Forecast */
            show_advanced_forecast: boolean;
            /**
             * Temperature Unit
             * @enum {string}
             */
            temperature_unit: "F" | "C";
            /**
             * Wind Unit
             * @enum {string}
             */
            wind_unit: "mph" | "kmh" | "mps" | "kt";
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            /** Precipitation Unit */
            precipitation_unit?: ("in" | "mm") | null;
            /** Show Advanced Forecast */
            show_advanced_forecast?: boolean | null;
            /** Temperature Unit */
            temperature_unit?: ("F" | "C") | null;
            /** Wind Unit */
            wind_unit?: ("mph" | "kmh" | "mps" | "kt") | null;
        };
        /** RainOutlook */
        RainOutlook: {
            /** Horizon Hours */
            horizon_hours: number;
            next_rain: components["schemas"]["RainWindow"] | null;
            /** Summary */
            summary: string;
        };
        /** RainWindow */
        RainWindow: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Expected Amount */
            expected_amount: number | null;
            /** High End Amount */
            high_end_amount: number | null;
            /** Peak Probability */
            peak_probability: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** Range */
        Range: {
            /** P10 */
            p10: number | null;
            /** P50 */
            p50: number | null;
            /** P90 */
            p90: number | null;
        };
        /** Spread */
        Spread: {
            /** P50 */
            p50: number | null;
            /** P90 */
            p90: number | null;
        };
        /** Summary */
        Summary: {
            /** Members */
            members: number | null;
            /** Next 24H Expected Precip */
            next_24h_expected_precip: number | null;
            /** Next 24H High */
            next_24h_high: number | null;
            /** Next 24H Low */
            next_24h_low: number | null;
            /** Next 24H Max Precip Probability */
            next_24h_max_precip_probability: number | null;
        };
        /** Units */
        Units: {
            /**
             * Precipitation
             * @enum {string}
             */
            precipitation: "in" | "mm";
            /**
             * Temperature
             * @enum {string}
             */
            temperature: "F" | "C";
            /**
             * Wind
             * @enum {string}
             */
            wind: "mph" | "kmh" | "mps" | "kt";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VisitorProfile */
        VisitorProfile: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Kind
             * @default anonymous
             * @constant
             */
            kind: "anonymous";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reverse_api_v1_geocode_reverse_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_geocode_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_locations_api_v1_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
        };
    };
    post_location_api_v1_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_location_api_v1_locations__location_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_location_api_v1_locations__location_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_api_v1_locations__location_id__forecast_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forecast"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_history_api_v1_locations__location_id__forecast_history_get: {
        parameters: {
            query?: {
                /** @description Target hour. Without an offset it is read in the location's timezone. */
                target_time?: string | null;
                /** @description Target local date (daily history). */
                target_date?: string | null;
                metric?: "temperature" | "precipitation" | "wind";
            };
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    update_preferences_api_v1_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
