import type { Forecast } from "@weather/api-types";
import raw from "./forecast.fixture.json";

/** A real API response (mock provider, Orlando, 2026-10-08 15:30Z), regenerated by hand when the schema changes. */
export const forecastFixture = raw as unknown as Forecast;
